[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
known_local_folder=['config',]

[tool.flake8]
max-line-length = 119
max-complexity = 18
ignore = "W293, W504, E111, E114, E402, E501,"
exclude = [".venv"]

[tool.autopep8]
max-line-length = 119
indent-size = 4
ignore = "E111, E114, E402, E501,"
in-place = true
recursive = true
aggressive = 3
